/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParicionesRouteImport } from './routes/pariciones'
import { Route as ConsultasRouteImport } from './routes/consultas'
import { Route as IndexRouteImport } from './routes/index'

const ParicionesRoute = ParicionesRouteImport.update({
  id: '/pariciones',
  path: '/pariciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultasRoute = ConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultas': typeof ConsultasRoute
  '/pariciones': typeof ParicionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultas': typeof ConsultasRoute
  '/pariciones': typeof ParicionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultas': typeof ConsultasRoute
  '/pariciones': typeof ParicionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consultas' | '/pariciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consultas' | '/pariciones'
  id: '__root__' | '/' | '/consultas' | '/pariciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultasRoute: typeof ConsultasRoute
  ParicionesRoute: typeof ParicionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pariciones': {
      id: '/pariciones'
      path: '/pariciones'
      fullPath: '/pariciones'
      preLoaderRoute: typeof ParicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultas': {
      id: '/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof ConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultasRoute: ConsultasRoute,
  ParicionesRoute: ParicionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
